### ISSUE TITLE
Methodology

### ISSUE THREAD

**Issue by MariaElFatihi** [nutellaweera/foodie-team-6#14]

**Comment by MariaElFatihi** [comment]
[methodology draft.docx](https://github.com/nutellaweera/foodie-team-6/files/8319251/methodology.draft.docx)

**Comment by MariaElFatihi** [comment]
[methodology draft.docx](https://github.com/nutellaweera/foodie-team-6/files/8354323/methodology.draft.docx)

**Comment by MariaElFatihi** [comment]
[methodology draft.docx](https://github.com/nutellaweera/foodie-team-6/files/8551659/methodology.draft.docx)

**Comment by MariaElFatihi** [comment]
Please if you could add the evaluation methods and testing to the latest methodology draft.
@mahaalbashir @nutellaweera

**Comment by nutellaweera** [comment]
[methodology.draft.docx](https://github.com/nutellaweera/foodie-team-6/files/8558101/methodology.draft.docx)

Added a testing and evaluation section. PFA ^.
